# Generated by Django 3.1 on 2020-08-05 00:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
